# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'useImage'
      link: '/usage/use-image'
    - label: 'useAudio'
      link: '/usage/use-audio'
    - label: 'useGif'
      link: '/usage/use-gif'
    - label: 'useVideo'
      link: '/usage/use-video'
    - label: 'useUpload'
      link: '/usage/use-upload'
    - label: 'useSearch'
      link: '/usage/use-search'
